In [1]:
from sklearn.linear_model import Lasso
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from sklearn.preprocessing import PolynomialFeatures
from sklearn.model_selection import GridSearchCV
from math import sqrt
from xgboost import XGBRegressor
from sklearn.ensemble import GradientBoostingRegressor, RandomForestRegressor


import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

plt.style.use('seaborn')

train = pd.read_csv('C:\\Users\\user\\workspace\\movie\\movies_train.csv')
test = pd.read_csv('C:\\Users\\user\\workspace\\movie\movies_test.csv')
submission = pd.read_csv('C:\\Users\\user\\workspace\\movie\\submission.csv')

In [2]:
X = train[['num_staff', 'time']]
y = train[['box_off_num']]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=121)

In [3]:
hyper_parameter = {
    'alpha' : [0.01, 0.1, 1, 10],
    'max_iter' : [100, 500, 1000, 1500, 2000]
}

In [4]:
lasso_model = Lasso()

In [5]:
hyper_parameter_tuner = GridSearchCV(lasso_model, hyper_parameter, cv=5)
hyper_parameter_tuner.fit(X, y)

GridSearchCV(cv=5, estimator=Lasso(),
             param_grid={'alpha': [0.01, 0.1, 1, 10],
                         'max_iter': [100, 500, 1000, 1500, 2000]})

In [6]:
hyper_parameter_tuner.best_params_

{'alpha': 10, 'max_iter': 100}

In [7]:
xgb = XGBRegressor(random_state = 42, alpha=10, max_iter=100)
gbr = GradientBoostingRegressor(random_state=42)
rf = RandomForestRegressor(random_state=42)
md_label = ['XGBRegressor', 'GradientBoostingRegressor', 'RandomForestRegressor']
all_md = [xgb, gbr, rf]

In [8]:
xgb.fit(X_train, y_train)

[20:55:03] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.5.1/src/learner.cc:576: 
Parameters: { "max_iter" } might not be used.

  This could be a false alarm, with some parameters getting used by language bindings but
  then being mistakenly passed down to XGBoost core, or some parameter actually being used
  but getting flagged wrongly here. Please open an issue if you find any such cases.




XGBRegressor(alpha=10, base_score=0.5, booster='gbtree', colsample_bylevel=1,
             colsample_bynode=1, colsample_bytree=1, enable_categorical=False,
             gamma=0, gpu_id=-1, importance_type=None,
             interaction_constraints='', learning_rate=0.300000012,
             max_delta_step=0, max_depth=6, max_iter=100, min_child_weight=1,
             missing=nan, monotone_constraints='()', n_estimators=100, n_jobs=6,
             num_parallel_tree=1, predictor='auto', random_state=42,
             reg_alpha=10, reg_lambda=1, scale_pos_weight=1, subsample=1,
             tree_method='exact', validate_parameters=1, verbosity=None)

In [9]:
gbr.fit(X_train, y_train)

C:\Users\user\anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


GradientBoostingRegressor(random_state=42)

In [10]:
rf.fit(X_train, y_train)

C:\Users\user\AppData\Local\Temp/ipykernel_15704/2725846524.py:1: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  rf.fit(X_train, y_train)


RandomForestRegressor(random_state=42)

In [11]:
xg_pred = xgb.predict(X_test)
gbr_pred = gbr.predict(X_test)
rf_pred = rf.predict(X_test)

In [12]:
xg_pred

array([ 1.45238250e+05,  1.06744600e+06,  4.87930000e+06,  6.71557422e+03,
        1.17261650e+06,  8.14210781e+04,  4.84983125e+04,  3.50733000e+06,
        7.14207000e+05,  1.04640166e+04,  1.33553652e+04,  2.41379370e+03,
        7.27943237e+02,  7.56300375e+05, -6.46470898e+04, -1.90844897e+03,
        2.14440450e+06,  1.53251523e+04,  3.37185325e+06,  3.61760825e+06,
        1.66744500e+05, -1.75116895e+04,  5.40078188e+05,  7.70781375e+05,
        5.11202750e+05,  3.66555781e+04, -1.81848682e+03,  1.82514469e+05,
       -3.98069336e+04,  1.73781387e+04,  1.46208850e+06,  4.48726875e+05,
        7.27943237e+02,  7.33598750e+05,  5.87733800e+06,  4.08856906e+05,
        6.45116699e+03,  1.13567375e+06,  1.71873988e+06,  9.39733906e+04,
        9.22256531e+02,  1.77433838e+06,  1.32346325e+06,  4.03718350e+06,
        9.71458000e+05,  1.36891828e+05,  1.14658888e+06,  9.86241699e+03,
        2.50375537e+03,  4.01049050e+06, -3.42653203e+04,  4.79099141e+04,
       -1.58937172e+05,  

In [13]:
gbr_pred

array([ 488062.73792245,  352569.24692615, 5033556.19914565,
         52419.84151021,  844018.2879776 ,   65910.70936787,
         65910.70936787, 2759190.88118359,  883351.97805534,
         65910.70936787,   71401.5154136 ,   44869.52503689,
         46102.43422758,   20867.32943725,   44869.52503689,
         44869.52503689, 2901504.27035007,   65910.70936787,
       3695245.7070936 , 4742700.04234206,   65910.70936787,
        101657.23553354,  526034.0634821 ,  487596.88068555,
        237670.15265957,   65910.70936787,   65910.70936787,
        300870.24834178,   44869.52503689,   65910.70936787,
       1116949.38566517, -235225.40803557,   46102.43422758,
        925942.56212554, 4957340.88524636,  798529.58250844,
         44869.52503689,   52419.84151021, 2969444.40656397,
        488062.73792245,   52419.84151021, 2376364.94419532,
       1632623.64008681, 3778480.47201771, 1084443.21566876,
         62091.42428893, 1418600.17766163,   91743.85591519,
         36673.53387806,

In [14]:
rf_pred

array([1.32892630e+05, 6.20525740e+05, 4.98102111e+06, 8.84323800e+03,
       7.37219960e+05, 6.20802600e+04, 5.69097400e+04, 3.59266267e+06,
       4.64277500e+05, 1.65744900e+04, 9.01383000e+03, 1.69031300e+03,
       6.19055000e+03, 3.66125270e+05, 1.41534347e+04, 1.02442633e+04,
       1.99533356e+06, 3.41593000e+03, 5.41336036e+06, 3.89002882e+06,
       3.17436300e+04, 7.20095750e+04, 4.92181130e+05, 6.66766790e+05,
       1.71686460e+05, 8.48292417e+04, 1.79653000e+03, 6.96350670e+05,
       1.10787500e+05, 2.55640000e+03, 1.62549334e+06, 1.12517416e+06,
       5.76295000e+03, 7.86184670e+05, 3.09029338e+06, 8.34072970e+05,
       3.56100333e+03, 1.97669260e+06, 2.42982616e+06, 1.32377360e+05,
       4.58363910e+03, 3.65711502e+06, 1.43732714e+06, 4.42822269e+06,
       7.02766470e+05, 4.36819830e+05, 1.27861767e+06, 2.14352000e+03,
       5.55011000e+03, 3.82809481e+06, 3.46045300e+04, 5.68544840e+05,
       8.11757810e+05, 5.59026463e+06, 1.35069628e+04, 1.42957747e+04,
      

In [15]:
mse1 = mean_squared_error(y_test, xg_pred)
mse2 = mean_squared_error(y_test, gbr_pred)
mse3 = mean_squared_error(y_test, rf_pred)

In [16]:
mse1

5778013744045.144

In [17]:
mse2

5081199051467.884

In [18]:
mse3

4345170755698.4907